name: test Project

on:
  pull_request:
    branches:
      -master
jobs:
  Test:
    runs-on: ubuntu-laster
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20
      - run: npm ci 
      - run: npm test 
      - run: npm run build 
